swagger: "2.0"
info:
  version: "0.0.1"
  title: Even Money Syndicate Services
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /login:
    x-swagger-router-controller: login
    post:
      description: Authenticates user provided credentials
      operationId: login
      parameters:
        - name: data
          in: body
          description: Json object in post body containing UserName and Password
          schema:
            $ref: '#/definitions/UserObject'
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/LoginResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /best_bets:
    x-swagger-router-controller: best_bets
    get:
      operationId: best_bets
      parameters:
        - in: query
          name: url
          description: URL
          type: string
          required: true
        - in: query
          name: elem
          description: HTML element
          type: string
          required: false
        - in: query
          name: id
          description: HTML element id
          type: string
          required: false
        - in: query
          name: clas
          description: HTML elemnt class
          type: string
          required: false
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/LoginResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /get_odds:
    x-swagger-router-controller: odds
    get:
      operationId: get_odds
      parameters:
        - in: query
          name: url
          description: URL
          type: string
          required: true
        - in: query
          name: elem
          description: HTML element
          type: string
          required: false
        - in: query
          name: id
          description: HTML element id
          type: string
          required: false
        - in: query
          name: clas
          description: HTML elemnt class
          type: string
          required: false
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/LoginResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  LoginResponse:
    required:
      - message
    properties:
      message:
        type: string
      token:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  UserObject:
    type: object
    required:
      - UserName
      - Password
    properties:
      UserName:
        type: string
        description: Username of the entity logging in
      Password:
        type: string
        description: Password of the entity logging in
